@startuml

class User {
    String name
    String email

    List<Project> getProjects()
    createProject(name)
}

class Role {
    String name
    String[] access
}

class Project {
    String name
    Map<User, Role> userWithRoles
    List<SoftwareComponent> softwareComponents
    Planning planning
}

Project "1" *-- "Many" Role
User "Many" -- "Many" Project

class SoftwareComponent {
    String name
    Planning planning
    Development development
    Build build
    Deploy deploy
    Production production
}

note right of SoftwareComponent
    SoftwareComponent is act as microservice.
end note

Project "1" *-- "Many" SoftwareComponent


@enduml