version: '3.7'
services:
  splunk:
    environment:
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=NQc376RUcE2ePrJ
    hostname: splunk
    image: opsforge/splunk-light
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    restart: always
